workspace extends model.dsl {
    name "Shared reference architecture"
    description "FireFly ecosystem, private Besu, security and Unleash references; C4 levels 1-3."
    !docs documentation/workspace
    !adrs decisions/adr
    !adrs decisions/workspace
    views {
        !include views/01-landscape.dsl
        !include views/02-context-firefly.dsl
        !include views/03-context-besu.dsl
        !include views/04-alternatives.dsl
        !include views/10-firefly-runtime.dsl
        !include views/11-firefly-state.dsl
        !include views/20-firefly-core-api.dsl
        !include views/20-firefly-core-identity.dsl
        !include views/20-firefly-core-messaging.dsl
        !include views/20-firefly-core-contracts.dsl
        !include views/20-firefly-core-events.dsl
        !include views/20-firefly-core-persistence.dsl
        !include views/30-firefly-evm-transactions.dsl
        !include views/30-firefly-evm-events.dsl
        !include views/40-firefly-signer.dsl
        !include views/40-firefly-dx.dsl
        !include views/40-firefly-erc20.dsl
        !include views/40-firefly-erc1155.dsl
        !include views/50-besu-network.dsl
        !include views/51-besu-network.dsl
        !include views/51-besu-consensus.dsl
        !include views/51-besu-execution.dsl
        !include views/60-applications.dsl
        !include views/61-tools.dsl
        !include views/62-sandbox.dsl
        !include views/68-sandbox-browser.dsl
        !include views/24-explorer-browser.dsl
        !include views/63-operations.dsl
        !include views/21-core-blockchain-adapters.dsl
        !include views/22-core-storage-adapters.dsl
        !include views/23-core-event-token-adapters.dsl
        !include views/31-evm-persistence-delivery.dsl
        !include views/77-other-evm-network.dsl
        !include views/12-embedded-storage-options.dsl
        !include views/70-option-ethconnect.dsl
        !include views/71-option-fabconnect.dsl
        !include views/72-option-tezosconnect.dsl
        !include views/73-option-cardanoconnect.dsl
        !include views/74-option-cordaconnect.dsl
        !include views/75-ethconnect-requests.dsl
        !include views/75-ethconnect-events.dsl
        !include views/75-fabconnect-transactions.dsl
        !include views/75-fabconnect-events.dsl
        !include views/75-tezosconnect-transactions.dsl
        !include views/75-tezosconnect-events.dsl
        !include views/75-cardanoconnect-operations.dsl
        !include views/75-cardanoconnect-contracts-events.dsl
        !include views/75-cardanosigner-signing.dsl
        !include views/75-cordaconnect-starter.dsl
        !include views/76-legacy-broker-options.dsl
        !include views/64-cli.dsl
        !include views/65-performance.dsl
        !include views/66-event-audit.dsl
        !include views/67-config-migration.dsl
        !include views/100-security-landscape.dsl
        !include views/100-security-keycloak-context.dsl
        !include views/100-security-keycloak-containers.dsl
        !include views/100-security-managedHsm-context.dsl
        !include views/100-security-managedHsm-containers.dsl
        !include views/100-security-cyberarkPam-context.dsl
        !include views/100-security-cyberarkPam-containers.dsl
        !include views/100-security-conjur-context.dsl
        !include views/100-security-conjur-containers.dsl
        !include views/100-security-entraId-context.dsl
        !include views/100-security-entraId-containers.dsl
        !include views/100-security-adDs-context.dsl
        !include views/100-security-adDs-containers.dsl
        !include views/100-security-adFs-context.dsl
        !include views/100-security-adFs-containers.dsl
        !include views/100-security-keycloak-server-components.dsl
        !include views/100-security-managedHsm-service-components.dsl
        !include views/100-security-cyberarkPam-vault-components.dsl
        !include views/100-security-cyberarkPam-pvwa-components.dsl
        !include views/100-security-cyberarkPam-cpm-components.dsl
        !include views/100-security-cyberarkPam-psm-components.dsl
        !include views/100-security-conjur-service-components.dsl
        !include views/100-security-conjur-synchronizer-components.dsl
        !include views/100-security-entraId-authentication-components.dsl
        !include views/100-security-entraId-directory-components.dsl
        !include views/100-security-entraId-provisioning-components.dsl
        !include views/100-security-entraId-agent-components.dsl
        !include views/100-security-adDs-directory-components.dsl
        !include views/100-security-adFs-service-components.dsl
        !include views/100-security-apps-hsmSigner-components.dsl
        !include views/100-security-example-login-ad.dsl
        !include views/100-security-example-broker-entra.dsl
        !include views/100-security-example-broker-adfs.dsl
        !include views/100-security-example-directory-sync.dsl
        !include views/100-security-example-privileged-access.dsl
        !include views/100-security-example-secret-delivery.dsl
        !include views/100-security-example-key-protection.dsl
        !include views/100-security-example-dlt-signing.dsl
        !include views/05-context-applications.dsl
        !include views/06-context-tools.dsl
        !include views/07-context-operations.dsl
        !include views/110-unleash-containers.dsl
        !include views/110-unleash-storage-alternatives.dsl
        !include views/110-unleash-ui-components.dsl
        !include views/110-unleash-server-administration.dsl
        !include views/110-unleash-server-configuration-delivery.dsl
        !include views/110-unleash-server-supporting-services.dsl
        !include views/110-unleash-edge-request-processing.dsl
        !include views/110-unleash-edge-synchronization-recovery.dsl
    }
}
